[workspace]
members = [
    "std",
    ".",
]
default-members = [
    "std",
    "."
]

[workspace.package]
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
homepage = "https://github.com/RGB-WG"
repository = "https://github.com/RGB-WG/rgb-wallet"
rust-version = "1.67" # Due to strict encoding library
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
amplify = "4.5.0"
baid58 = "0.4.4"
strict_encoding = "2.6.1"
strict_types = "1.6.3"
commit_verify = { version = "0.10.6", features = ["stl"] }
bp-core = { version = "0.10.11", features = ["stl"] }
rgb-core = { version = "0.10.8", features = ["stl"] }

[package]
name = "rgb-wallet"
version = "0.10.9"
description = "RGB wallet library for smart contracts on Bitcoin & Lightning network"
keywords = ["bitcoin", "lightning", "rgb", "smart-contracts", "lnp-bp"]
categories = ["cryptography::cryptocurrencies"]
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
readme = "README.md"
exclude = [".github", "std"]

[lib]
name = "rgbwallet"
crate-type = ["cdylib", "rlib"] # We need this for WASM

[dependencies]
amplify = { workspace = true }
baid58 = { workspace = true }
commit_verify = { workspace = true }
strict_encoding = { workspace = true }
# descriptor-wallet = "0.10.0-alpha.1"
bp-core = { workspace = true }
rgb-core = { workspace = true }
rgb-std = { version = "0.10.8", path = "std" }
fluent-uri = "0.1.4"
indexmap = "2.0.2"
# TODO: This dependencies should be replaced with psbt package
bitcoin = "0.30.1"
chrono = "0.4.24"
percent-encoding = "2.2.0"

[features]
default = []
all = ["fs", "serde"]
serde = ["rgb-std/serde", "rgb-core/serde"]
fs = ["rgb-std/fs"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
rand = { version = "0.8.4", optional = true }
getrandom = { version = "0.2", features = ["js"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[package.metadata.docs.rs]
features = [ "all" ]

[patch.crates-io]
commit_verify = { path = "../client_side_validation/commit_verify" }
